---
language: python
services: docker

env:
  global:
    - ROLE_NAME: jenkins_casc
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: fedora27
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: centos7
      MOLECULE_PLAYBOOK: playbook-template.yml

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME mattandes.$ROLE_NAME
  - cd mattandes.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
