# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Use the below image as our base since it has the vBox guest additions in it already
    config.vm.box = "geerlingguy/centos7"

    # Define VM's hostname
    config.vm.hostname = "test-box"

    # Forward the port for Jenkins
    config.vm.network "forwarded_port", guest: 8080, host: 8888

    # Use the default Vagrant key instead of generating a new one on provisioning
    config.ssh.insert_key = false
  
    # Install Git and Ansible
    config.vm.provision "shell", inline: <<-SHELL
      yum install -y git yum-utils epel-release
      sed -i '0,/metalink/{s/metalink/#metalink/}' /etc/yum.repos.d/epel.repo
      yum-config-manager --setopt=epel.baseurl='http://mirror.sjc02.svwh.net/fedora-epel/7/$basearch' --save
      yum install -y ansible
    SHELL

    # Map our role directory to a directory in the ansible roles directory for easy testing of roles
    config.vm.synced_folder "../", "/etc/ansible/roles/role_under_test", type: "virtualbox"#, disabled: true

    # Run Ansible test playbook inside the VM
    config.vm.provision "ansible_local" do |ansible|
        ansible.install = false
        ansible.playbook = "playbook.yml"
        ansible.galaxy_role_file = "requirements.yml"
        ansible.limit = "all,localhost"
      end
  end